name: Package test files
on:
  workflow_dispatch:
    inputs:
      CPU:
        description: "分支"
        required: true
        default: 'sm8475'
      FEIL:
        description: "配置文件"
        required: true
        default: 'oneplus_11r_v'
      CPUD:
        description: "处理器代号"
        required: true
        default: 'waipio'
      ANDROID_VERSION:
        description: "内核安卓版本"
        required: true
        default: 'android12'
      KERNEL_VERSION:
        description: "内核版本"
        required: true
        default: '5.10'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure Git
        run: |
         git config --global user.name "build"
         git config --global user.email "3436378798@qq.com"

      - name: Download latest susfs4ksu module
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          curl -sSLH "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/sidex15/susfs4ksu-module/releases/latest
