name: Download SUSFS Module

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Latest Release
        env:
          GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}  # 引用自定义 Secret
        run: |
          # 获取最新版本的下载链接
          LATEST_URL=$(curl -sSLH "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/sidex15/susfs4ksu-module/releases/latest \
            | jq -r '.assets[] | select(.name | test("ksu_module_susfs_1.5.2\\+.*\\.zip")) | .browser_download_url')

          # 下载文件
          curl -LO "$LATEST_URL"

          # 验证文件存在性
          if [ ! -f *.zip ]; then
            echo "Error: File not downloaded!"
            exit 1
          fi
